version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes: 
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports: 
      - 9090:9090
    networks:
      - grafana_monitoring


networks:
  grafana_monitoring:
    external: true