global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: 
rule_files:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "node_exporter"
    static_configs:
      # - targets: ['web.ofwa.local:9100']
      - targets: ['172.16.222.10:9100']
  - job_name: 'snmp_exporter'
    static_configs:
      - targets: ['192.168.0.1']
    metrics_path: /snmp
    params:
        module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9116