version: "3"

services:
  
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    hostname: influxdb
    restart: unless-stopped
    volumes:
      - influxdb-data:/var/lib/influxdb2
      # - ./config.yml:/etc/influxdb2/config.yml:ro
      # - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
      # - /mnt/docker-volumes/Influxdb/init:/docker-entrypoint-initdb.d
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=influxdb
    ports:
      - 8086:8086
    networks:
      - grafana_monitoring

  
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    hostname: telegraf
    restart: unless-stopped
    user: telegraf:112 # see: https://www.influxdata.com/blog/docker-run-telegraf-as-non-root/
    command: 
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
      # - /etc:/hostfs/etc:ro
      # - /proc:/hostfs/proc:ro
      # - /sys:/hostfs/sys:ro
      # - /var/run/utmp:/var/run/utmp:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
      - INFLUX_TOKEN=h9fQv8zGkNIqlnukHuT3K51wrkj7z0jOO_W8aoJgZsWkhEqouUnoNAcNuErRM-sYr0H-2w4Kdhh


networks:
  grafana_monitoring:
    external: true

volumes:
  influxdb-data:
    external: true