version: "3.9"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1-debian
    container_name: uptime-kuma
    hostname: uptime-kuma
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  uptime-kuma:
    external: true